version: '3'

services:
  app:
    build: .
    env_file:
      - .env
      - .secrets
    volumes:
      - .:/opt/app
      - package_data:/venv
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
      - .secrets
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  package_data:
